### ISSUE TITLE
Windows: Can't interrupt the kernel when stuck in an infinite loop

### ISSUE THREAD

**Issue by rbeesley** [clojupyter/clojupyter#105]
Create a cell with the following code:

```clojure
(iterate inc 1)
```

If you run this, the java process will loop continuously with no exit condition for the iterator. It would be expected that "Interrupt the kernel" would stop executing the cell and return to the Jupyter Notebook UI. It doesn't, and you have to kill the external Java process.

Doing the same thing with a Python kernel:

```python
while True:
    pass
```

You can use "Interrupt the kernel," either by clicking the stop button or issuing the command from the command pallet, so it looks as though this is a signal which could be passed to the kernel and may not be processed by Clojupyter right now.

**Comment by klausharbo** [comment]
Interesting.  This works on Mac and Linux, but I just tried on Windows and, you're right, it doesn't work.  Clojupyter uses `beckon` to set up interrupt handlers, but apparently that does not work on Windows. 

I took a quick look and the [Jupyter protocol specification](https://jupyter-client.readthedocs.io/en/stable/messaging.html) does in fact mention that you can set `interrupt_mode` to `true` and get `interrupt_request` packets instead of receiving a signal which is the way we currently support interrupts.  I suppose that would be how to support it on Windows.

**Comment by klausharbo** [comment]
Addressed in 0.3.0 - closed
