### ISSUE TITLE
Plan for error in demo-jupyter-notebook-only

### ISSUE THREAD

**Issue by zackteo** [clojupyter/clojupyter#127]
> OBS The cell above fails to render the resulting Vega graph. Needs fixing.

Am trying out clojupyter and was running the examples. Am wondering how the above can be fixed :o 

Also another 2 questions:
1. Is there a way to load dependencies faster?
2. Based on the way dependencies are loaded, for converting a notebook to "production" code do I simply need to make changes to that?

**Comment by nighcoder** [comment]
> Okay. Will check the jupyter-lab way! (But yeah still wondering if anyone intends to fix the part that says "Needs fixing" hahaha)

Well, if you get to work you can submit a PR. When I worked on ipywidgets I used jupyter lab and fixed the lab example. I've looked at the notebook example but I've seen no obvious solution and didn't spend more time on it, since I didn't plan to using notebook. Honestly, the best solution I see is to drop support altogether for one of the editors, since this project doesn't have nearly enough workforce to support two different code editors.

> Sorry where do you find helper/add-dependencies is this in jupyter notebook? That looks like .clojure/deps.edn ? But that's not related(?)

Clojupyter has a namespace `clojupyter.misc.helper`, where you'll find `add-dependencies` fn to help managing dependencies from the notebook (at runtime). If you didn't know about it, how did you load the dependencies the *slow* way?

As for two, there's a whole rabbit hole to explore there. I've made a proof of concept (a dirty hack) to Clojupyter to make is connect to remote nrepl server, thus moving the responsibility of environment setup to your project managements tools. If there's a need for it, it can be cleaned up and turned into a feature.

I'm not sure about the Clojure / Python / R interop, but there's an active community of Clojure developers working on bridging those gaps on [zulip chat](https://clojurians.zulipchat.com/#narrow/stream/151924-data-science).

**Comment by krukow** [comment]
Hey - apologies for the late reply - I'm maintaining this in my spare time.

You can also use this as a library - here's an example: https://github.com/krukow/edmondson 

In that case you can add additional dependencies in that project and make everything available without downloading on the fly.

Does that help?

**Comment by krukow** [comment]
Closing: I will not be able to support releasing to Conda and all users should be familar with clojars since this is a clojure project.
