### ISSUE TITLE
When errors happen in the code, `execute_reply` messages are not sent

### ISSUE THREAD

**Issue by NightMachinary** [clojupyter/clojupyter#140]
I am not too familiar with Jupyter kernels, but from what I have observed from the other kernels, in reply to an `execute_request`, there should always be an `execute_reply` message, even if errors happen. I don't get this message from clojupyter kernels.

PS: I am using `jupyter-kernel-gateway` to communicate with the kernels, but I don't think that matters.

**Comment by nighcoder** [comment]
Can confirm, jupyter standard requires that every `execute_request` should generate `execute_reply` and clojupyter doesn't do that if the executed code raised an exception.

@NightMachinary thanks for reporting the issue. Do you have any issues with your current setup, because as I see it, depending on the front end implementation this could barely be visible to the end user, or it can blow up in their face?

I have tested it with jupyter qtconsole and after executing code that raises an exception I can't get back a prompt. This might be related to this issue right here.

**Comment by NightMachinary** [comment]
@nighcoder This bug was quite fatal to my project; I could not release the kernel to receive further execution requests until the current request was terminated, and I relied on the execute_reply message to confirm the termination.

**Comment by nighcoder** [comment]
@NightMachinary. This should get fixed in #145. In the mean time, you can test the fix by compiling the [up-master branch](https://github.com/nighcoder/clojupyter/tree/up-master).

**Comment by NightMachinary** [comment]
Thanks. (I’ll reopen if issues are found.)
