### ISSUE TITLE
Bump Version

### ISSUE THREAD

**Issue by slavad** [clojupyter/clojupyter#142]
Could you also change version in `resources/clojupyter/assets/version.edn` to 0.4.0?

Could also somebody add me to the collaborators? In that case I can create a PR on my own.

**Comment by nighcoder** [comment]
Hi everybody, I'm back.

I've started working on the develop branch, mainly cleaning up the namespaces and separating the building environment from the actual kernel.

No actual changes were made to the functionality of the kernel so far (except for the message signing bug fix) and it compiles, installs and all tests pass.

It does, however, remove the `cmdline` from the jar deployed on clojars, so If you're relying on it to build your custom kernel, you won't be able to do that in the future. @krukow, I understand that that is your use case. How does the new build system affects your use case? Is it straightforward to adapt your custom changes to a plugin that can be installed along side standard clojupyter kernel?

@slavad, did the fixes to message signing solve your issues? These should be available on the `master` already so you shouldn't depend on the `develop` branch.

**Comment by slavad** [comment]
@nighcoder  yes, all works now, thx

**Comment by krukow** [comment]
@nighcoder I will figure out how to make this work for me - I'd love to land your changes. Please go ahead 🙏🏻

**Comment by nighcoder** [comment]
I've added a new PR that brings the necessary changes to `CommAtom`. Check it out at #147

@krukow, I know this might be overwhelming, so I'm available for any questions. I'm also leaving it as draft for now, because I want to test it more thoroughly in the days to come. I'm sure that it hides some bugs that I've yet to clear.

Everyone else is encouraged to try it out. Here is a quick how to that you can use as a reference:

Clone the repository if you haven't done so already:
> git clone https://github.com/nighcoder/clojupyter.git

Switch to `feature/plugins-pr` branch
> cd clojupyter
> git checkout feature/plugins-pr

Compile the source code
> lein metajar

and install it
> bin/install

Confirm that the kernel has installed by listing all the clojure installed kernels:
> bin/list

Install  it to your local Maven repository so you can reference it as a dependency in your projects:
> lein install

Clone the widgets library:
> git clone https://github.com/nighcoder/widgets.git
> cd widgets

Compile the widgets library
> lein metajar

Install the library
> bin/install clojupyter-0.4.0-alpha0

Install the widget plugin for your **jupyter notebook** / **jupyter lab** front end. See instructions [here](https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/user_install.md#installation).
I think that installing the `ipywidgets` python package installs automatically the required front-end extensions, so you may skip this step if you have the right extensions installed.
You can see the list of installed front-end extensions with:
> jupyter labextension list
> jupyter nbextension list

Get back to your `clojupyter` directory and enable your newly installed plugin with
> bin/enable-plugin widgets

Start your Jupyter Lab or Notebook and open the `example` directory in the `widgets` project. You can see there all of the models and some mode advanced interaction.

**Comment by nighcoder** [comment]
> > For the rest of maintainers, it will be nice to have a way to get in
> > contact with each other for organising purposes. Something like a mailing
> > list or an IRC channel.
> 
> Agreed, I can set something up over the course of next month or so.

@krukow, I just noticed the **Discussions** tab. [Next.js](https://github.com/vercel/next.js/discussions) is a project that's been using it since beta and it looks like it pretty much meets our needs. It's an open forum where we can discuss ideas at depth about the project, post announcements and other news without opening new issues. This way we can keep the issues list relatively clean and treat each issue as a ticket that needs some sort of action to close it. It also has the advantage of better integration with the project's history, files, issues etc. over some third party service.

It looks like I can activate it myself, but I don't feel like imposing a new workflow as the newcomer to the project, so I want to hear the opinion of the rest of the team @roryk @klausharbo @luojieshun @aria42 and all the others that I'm missing since I can't find a way to list all the maintainers of the project.

**Comment by krukow** [comment]
Discussions enabled: https://github.com/clojupyter/clojupyter/discussions - let's just try this out

**Comment by krukow** [comment]
Closing: version bumped on master branch and released 0.3.6: https://clojars.org/clojupyter
