### ISSUE TITLE
Windows compatible makefile

### ISSUE THREAD

**Issue by AlexGoico** [clojupyter/clojupyter#16]
Perhaps even replace it with a python/clojure script for portability.

**Comment by roryk** [comment]
Hi @typedeph,

Thanks-- sorry, I don't know anything out Windows at all!

**Comment by pdenno** [comment]
Likewise, I don't know Windows. Would really like to see this though. My son would like to learn Clojure; I think it would be easier to start with clojupyter rather than emacs. Regarding @typedeph comment about python script, is there an example someone could point to?

**Comment by typedeph** [comment]
I've been writing a Python script I had thought about contributing but have been busy with other things and have not finished it, perhaps it could be a good starting to point or you could finish it if your thinking about contributing. It's basically a raw conversion of the bash script. 

There are a few things that I still need(ed) to consider such as how to deal with the bash script that the Makefile appends to the jar file. I didn't even know this was possible until I saw this project, its basically a script that runs before the jar. This feature is not possible on Windows, thus I was thinking about wrapping another python script to simulate the same activity.


You can view what I have so far under my fork. Its the install.py file.

**Comment by BeMxself** [comment]
I have installed on Windows manually:
1. Install MinGW, add child folder 'bin' to system variable PATH
2. Use 'mingw32-make' instead of 'make', or you can rename 'mingw32-make.exe' to 'make.exe'
3. Install clojupyter step by step, because windows don't support character '~', step 4 'make install' will fail, Don't worry, we can do follow step manually.
4. Copy file 'clojupyter/resources/kernel.json' to '%APPDATA%/jupyter/kernels/clojure'(create folder if missing)
5. Edit 'kernel.json', line 2: 
>   "argv": ["bash", "**full-path-of-clojupyter/clojupyter/bin/clojupyter**", "{connection_file}"]

change bold text to your actual file path
6. run bash (NOT cmd), type `jupyter-notebook ` ENTER

**Comment by BeMxself** [comment]
I don't know how to write make file, wish somebody do that.

**Comment by roryk** [comment]
Hi Song,

Thanks, that's great! Could you put those instructions into the README and open a pull request?

**Comment by BeMxself** [comment]
@roryk 
Sure, I'm glad to do it.
I'll check those steps first and then update the README.

**Comment by BeMxself** [comment]
#28

**Comment by klausharbo** [comment]
Clojupyter should now work on Windows as well as MacOS and Linux.  Clojure's support for Windows leaves something to be desired, but Clojupyter should work just fine.  Closing issue.
