### ISSUE TITLE
add-javascript function broken?

### ISSUE THREAD

**Issue by metasoarous** [clojupyter/clojupyter#76]
I'm working on #75 (as part of the [oz](https://github.com/metasoarous/oz) library: metasoarous/oz#33), and seem to be having trouble getting the `clojupyter.misc.helper/add-javascript` function to work. In fact, this function appears to not be working on one of the official clojupyter examples connecting to the Highcharts library. Note the console errors below:

![image](https://user-images.githubusercontent.com/88556/51080196-049ad800-168c-11e9-8f76-a70f001ab999.png)

Any idea what might be causing this? I think if I had this function working, this oz feature would be in the bag.

**Comment by metasoarous** [comment]
Interesting...

@mikeyford Would you mind chiming in here and indicating whether you're observing the same behavior I am?

Could this be a version-specific issue? I just downloaded and installed clojupyter & friends, so everything should be pretty recent:

![image](https://user-images.githubusercontent.com/88556/51132058-227c5000-17e6-11e9-8ad1-539f76349204.png)

From the console it looks like highcharts is being requested successfully (status 200). Also, I looked into how `add-javascript` works and it's basically just inserting a script into the result container, like so

![image](https://user-images.githubusercontent.com/88556/51132629-9e2acc80-17e7-11e9-9dde-abddb302a3b6.png)

I noticed that Jupyter has a notion of trusted/untrusted notebooks, and I thought that this might explain why the script isn't being evaluated, but after marking as trusted, I'm still seeing the same behavior.

Anyone have a clue what's going on here?

**Comment by jtcbrule** [comment]
For what it's worth, I'm observing the same issue. Version info:

The version of the notebook server is: 5.6.0
The server is running on this version of Python:

Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]

Current Kernel Information:

Clojupyters-0.1.0

**Comment by roryk** [comment]
Thanks-- are you all still experiencing this issue if you update to master?

**Comment by klausharbo** [comment]
Yes, as far as I can determine, `add-javascript` is indeed broken, the reason is that Jupyter at some point decided to not interpret `script` tags directly.  They use RequireJS instead, which seems to me to be a sensible solution.  It does mean that the approach taken by  `add-javascript` will not work in the future.

On the `develop` branch I have added (a proposal for) a replacement implementation of `add-javascript` based on RequireJS (aka Asynchronuous Module Definitions).  It seems to work but I'm not sure if it does all we need, so for now it resides in `clojupyter.javascript.alpha`.    

`examples/highcharts-demo.ipynb` on the branch contains the Highcharts example done with the new implementation, essentially you need to do

```
(cjpjs/amd-add-javascript-html
  [{:ident :hicharts :exports "Highcharts" :url "https://code.highcharts.com/highcharts"}])
```
to declare the Javascript library, and define something like

```
(defn highchart-chart
  [nodeid data]
  (cjpjs/amd-wrap-require [:hicharts]
    (format "function(hc){hc.chart('%s',%s)}" nodeid (json/write-str data))))
```
to use functions (cf. [RequireJS](https://requirejs.org) for details).

[Clearly Christopher (@metasoarous) already worked this out, as Oz contains interfacing code to clojupyter using something similar...]

Closed.

-Klaus.
