### ISSUE TITLE
Hanging after evaluating cell with syntax error

### ISSUE THREAD

**Issue by behrica** [clojupyter/clojupyter#83]
After evaluating a cell with syntax error I always get an exception in the shell and the notebook hangs.
Stacktrace:

Very easy to reproduce even with empty notebook and adding "aaaa" into first cell.

```
19-03-04 16:46:26 gandalf INFO [clojupyter.misc.messages:101] - send-message sending:  {:name "stderr",
 :text
 "Syntax error compiling at (REPL:2:35).\nUnable to resolve symbol: word-cloud-spec-fromtext in this context\n"}
19-03-04 16:46:25 gandalf INFO [clojupyter.misc.messages:101] - send-message sending:  {:execution_count 14N,
 :code
 "(defn filtered-word-cloud [sentiment]\n    (oz.notebook.clojupyter/view! (word-cloud-spec-fromtext \n                                      (map #(:Phrase %) (take sample-size (filter #(= sentiment (:Sentiment %)) train))))))"}

19-03-04 16:46:26 xxx INFO [clojupyter.misc.messages:105] - send-message: message sent
19-03-04 16:46:26 xxxx INFO [clojupyter.misc.nrepl-comm:116] - nrepl status  ["eval-error"]
19-03-04 16:46:26 xxxxx INFO [clojupyter.misc.nrepl-comm:116] - nrepl status  nil
19-03-04 16:46:26 xxxx INFO [clojupyter.misc.messages:101] - send-message sending:  {:name "stderr",
 :text
 "Syntax error compiling at (REPL:2:35).\nUnable to resolve symbol: word-cloud-spec-fromtext in this context\n"}
19-03-04 16:46:26 xxxx INFO [clojupyter.misc.messages:105] - send-message: message sent
19-03-04 16:46:26 xxxx INFO [clojupyter.misc.nrepl-comm:116] - nrepl status  ["done"]
ERROR: Unhandled REPL handler exception processing message {:id a6fd369a-e6ca-4d4a-ba8c-e57b87d21c83, :op stacktrace, :session 05fa475a-7fba-4b6e-928a-e24382396020}
java.lang.NullPointerException
	at clojure.string$replace_first.invokeStatic(string.clj:165)
	at clojure.string$replace_first.invoke(string.clj:138)
	at cider.nrepl.middleware.stacktrace$relative_path.invokeStatic(stacktrace.clj:195)
	at cider.nrepl.middleware.stacktrace$relative_path.invoke(stacktrace.clj:189)
	at cider.nrepl.middleware.stacktrace$extract_location.invokeStatic(stacktrace.clj:209)

**Comment by klausharbo** [comment]
Yes, this is a known problem, unfortunately.  I'm pretty sure it is caused by an issue in `cider-nrepl` (cf.[`nrepl` issue #549](https://github.com/clojure-emacs/cider-nrepl/issues/549) for example).  I haven't yet taken a serious stab at solving it as I am hoping it will soon take of itself...  The version of `nrepl` in clojupyter right now is "0.5.3" and the latest release is "0.6.0", it is conceivable that is solved there, but I haven't tried it just yet.  (Anyone interested in taking at look at it are more than welcome, of course!).  

I decided to not let this problem, which I also encounter, stop the release of the Clojure 1.10 code. To compensate, since it's really annoying to have your kernel exit in middle of a session, I added **control over whether or not the kernel should attempt to print a stacktrace**.   Quoting from `Changelog.md`:

  * `stacktrace.clj`
      * Add mechanism to control whether stacktraces are printed or not as it appears
        that `cider-nrepl` occasionally triggers uncaught exceptions. Most likely linked to upgrade of
       `nrepl` and/or `cider-nrepl`; the cause of the problem not understood as yet.

So, for now, you can call `clojupyter.misc.stacktrace/set-print-stacktraces!` with a truthy value to tell the kernel to try printing stacktraces, and a falsey value to tell it not to.  `clojupyter.misc.stacktrace/printing-stacktraces?` will tell you about current status.  The default is for it try, as you have already discovered.  It is not great, but better than nothing.  I tend disable stacktraces in my sessions, even if stacktraces are  occasionally useful that is less bad than a terminating kernel.  It did not seem right to turn them off by default (it is a trivial change to make not printing stacktraces the default if we decide we prefer that).

-Klaus.

**Comment by klausharbo** [comment]
Given the problem with uncaught 'op' stacktrace exceptions I think it is better to have default behaviour be NOT printing stacktraces, so I just deployed a small patch making that change.  I believe this means that you would not see your kernel terminate like shown above.

Longer term the underlying problem with uncaught exceptions needs to be addressed, of course.  I think this can be accomplished by upgrading to nREPL v0.6, but I haven't had time to try that yet.

-Klaus.
